//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.GroupService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfint", Namespace="http://schemas.datacontract.org/2004/07/Service.Utils")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BackOffice.GroupService.Group))]
    public partial class BaseEntityOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Service.Models")]
    [System.SerializableAttribute()]
    public partial class Group : BackOffice.GroupService.BaseEntityOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GroupService.GroupContract")]
    public interface GroupContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/GetByIdResponse")]
        BackOffice.GroupService.Group GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/GetByIdResponse")]
        System.Threading.Tasks.Task<BackOffice.GroupService.Group> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/InsertResponse")]
        BackOffice.GroupService.Group Insert(BackOffice.GroupService.Group entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/InsertResponse")]
        System.Threading.Tasks.Task<BackOffice.GroupService.Group> InsertAsync(BackOffice.GroupService.Group entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/UpdateResponse")]
        BackOffice.GroupService.Group Update(BackOffice.GroupService.Group entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/UpdateResponse")]
        System.Threading.Tasks.Task<BackOffice.GroupService.Group> UpdateAsync(BackOffice.GroupService.Group entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/SearchForResponse")]
        BackOffice.GroupService.Group[] SearchFor(System.Func<BackOffice.GroupService.Group, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/SearchForResponse")]
        System.Threading.Tasks.Task<BackOffice.GroupService.Group[]> SearchForAsync(System.Func<BackOffice.GroupService.Group, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/GetAllResponse")]
        BackOffice.GroupService.Group[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Group/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Group/GetAllResponse")]
        System.Threading.Tasks.Task<BackOffice.GroupService.Group[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupContractChannel : BackOffice.GroupService.GroupContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupContractClient : System.ServiceModel.ClientBase<BackOffice.GroupService.GroupContract>, BackOffice.GroupService.GroupContract {
        
        public GroupContractClient() {
        }
        
        public GroupContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BackOffice.GroupService.Group GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<BackOffice.GroupService.Group> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public BackOffice.GroupService.Group Insert(BackOffice.GroupService.Group entity) {
            return base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.GroupService.Group> InsertAsync(BackOffice.GroupService.Group entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public BackOffice.GroupService.Group Update(BackOffice.GroupService.Group entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.GroupService.Group> UpdateAsync(BackOffice.GroupService.Group entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public BackOffice.GroupService.Group[] SearchFor(System.Func<BackOffice.GroupService.Group, bool> predicate) {
            return base.Channel.SearchFor(predicate);
        }
        
        public System.Threading.Tasks.Task<BackOffice.GroupService.Group[]> SearchForAsync(System.Func<BackOffice.GroupService.Group, bool> predicate) {
            return base.Channel.SearchForAsync(predicate);
        }
        
        public BackOffice.GroupService.Group[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BackOffice.GroupService.Group[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
