//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.DepartmentProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfint", Namespace="http://schemas.datacontract.org/2004/07/Service.Utils")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BackOffice.DepartmentProxy.Department))]
    public partial class BaseEntityOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://schemas.datacontract.org/2004/07/Service.Models")]
    [System.SerializableAttribute()]
    public partial class Department : BackOffice.DepartmentProxy.BaseEntityOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartmentProxy.DepartmentContract")]
    public interface DepartmentContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/GetByIdResponse")]
        BackOffice.DepartmentProxy.Department GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/GetByIdResponse")]
        System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/InsertResponse")]
        BackOffice.DepartmentProxy.Department Insert(BackOffice.DepartmentProxy.Department entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/InsertResponse")]
        System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department> InsertAsync(BackOffice.DepartmentProxy.Department entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/UpdateResponse")]
        BackOffice.DepartmentProxy.Department Update(BackOffice.DepartmentProxy.Department entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/UpdateResponse")]
        System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department> UpdateAsync(BackOffice.DepartmentProxy.Department entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/SearchForResponse")]
        BackOffice.DepartmentProxy.Department[] SearchFor(System.Func<BackOffice.DepartmentProxy.Department, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/SearchForResponse")]
        System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department[]> SearchForAsync(System.Func<BackOffice.DepartmentProxy.Department, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/GetAllResponse")]
        BackOffice.DepartmentProxy.Department[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Department/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Department/GetAllResponse")]
        System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DepartmentContractChannel : BackOffice.DepartmentProxy.DepartmentContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentContractClient : System.ServiceModel.ClientBase<BackOffice.DepartmentProxy.DepartmentContract>, BackOffice.DepartmentProxy.DepartmentContract {
        
        public DepartmentContractClient() {
        }
        
        public DepartmentContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BackOffice.DepartmentProxy.Department GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public BackOffice.DepartmentProxy.Department Insert(BackOffice.DepartmentProxy.Department entity) {
            return base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department> InsertAsync(BackOffice.DepartmentProxy.Department entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public BackOffice.DepartmentProxy.Department Update(BackOffice.DepartmentProxy.Department entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department> UpdateAsync(BackOffice.DepartmentProxy.Department entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public BackOffice.DepartmentProxy.Department[] SearchFor(System.Func<BackOffice.DepartmentProxy.Department, bool> predicate) {
            return base.Channel.SearchFor(predicate);
        }
        
        public System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department[]> SearchForAsync(System.Func<BackOffice.DepartmentProxy.Department, bool> predicate) {
            return base.Channel.SearchForAsync(predicate);
        }
        
        public BackOffice.DepartmentProxy.Department[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BackOffice.DepartmentProxy.Department[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
