//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.InvitationProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfint", Namespace="http://schemas.datacontract.org/2004/07/Service.Utils")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BackOffice.InvitationProxy.Invitation))]
    public partial class BaseEntityOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Invitation", Namespace="http://schemas.datacontract.org/2004/07/Service.Models")]
    [System.SerializableAttribute()]
    public partial class Invitation : BackOffice.InvitationProxy.BaseEntityOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FromUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToUserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FromUserId {
            get {
                return this.FromUserIdField;
            }
            set {
                if ((this.FromUserIdField.Equals(value) != true)) {
                    this.FromUserIdField = value;
                    this.RaisePropertyChanged("FromUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToUserId {
            get {
                return this.ToUserIdField;
            }
            set {
                if ((this.ToUserIdField.Equals(value) != true)) {
                    this.ToUserIdField = value;
                    this.RaisePropertyChanged("ToUserId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InvitationProxy.InvitationContract")]
    public interface InvitationContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetByIdResponse")]
        BackOffice.InvitationProxy.Invitation GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetByIdResponse")]
        System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/InsertResponse")]
        BackOffice.InvitationProxy.Invitation Insert(BackOffice.InvitationProxy.Invitation entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/InsertResponse")]
        System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation> InsertAsync(BackOffice.InvitationProxy.Invitation entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/UpdateResponse")]
        BackOffice.InvitationProxy.Invitation Update(BackOffice.InvitationProxy.Invitation entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/UpdateResponse")]
        System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation> UpdateAsync(BackOffice.InvitationProxy.Invitation entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/SearchForResponse")]
        BackOffice.InvitationProxy.Invitation[] SearchFor(System.Func<BackOffice.InvitationProxy.Invitation, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/SearchForResponse")]
        System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation[]> SearchForAsync(System.Func<BackOffice.InvitationProxy.Invitation, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetAllResponse")]
        BackOffice.InvitationProxy.Invitation[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_Invitation/GetAllResponse")]
        System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation[]> GetAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvitationContractChannel : BackOffice.InvitationProxy.InvitationContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvitationContractClient : System.ServiceModel.ClientBase<BackOffice.InvitationProxy.InvitationContract>, BackOffice.InvitationProxy.InvitationContract {
        
        public InvitationContractClient() {
        }
        
        public InvitationContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvitationContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvitationContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvitationContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BackOffice.InvitationProxy.Invitation GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public BackOffice.InvitationProxy.Invitation Insert(BackOffice.InvitationProxy.Invitation entity) {
            return base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation> InsertAsync(BackOffice.InvitationProxy.Invitation entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public BackOffice.InvitationProxy.Invitation Update(BackOffice.InvitationProxy.Invitation entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation> UpdateAsync(BackOffice.InvitationProxy.Invitation entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public BackOffice.InvitationProxy.Invitation[] SearchFor(System.Func<BackOffice.InvitationProxy.Invitation, bool> predicate) {
            return base.Channel.SearchFor(predicate);
        }
        
        public System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation[]> SearchForAsync(System.Func<BackOffice.InvitationProxy.Invitation, bool> predicate) {
            return base.Channel.SearchForAsync(predicate);
        }
        
        public BackOffice.InvitationProxy.Invitation[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BackOffice.InvitationProxy.Invitation[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
    }
}
