//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOffice.UserProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfint", Namespace="http://schemas.datacontract.org/2004/07/Service.Utils")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BackOffice.UserProxy.User))]
    public partial class BaseEntityOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt {
            get {
                return this.CreatedAtField;
            }
            set {
                if ((this.CreatedAtField.Equals(value) != true)) {
                    this.CreatedAtField = value;
                    this.RaisePropertyChanged("CreatedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedAt {
            get {
                return this.UpdatedAtField;
            }
            set {
                if ((this.UpdatedAtField.Equals(value) != true)) {
                    this.UpdatedAtField = value;
                    this.RaisePropertyChanged("UpdatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Service.Models")]
    [System.SerializableAttribute()]
    public partial class User : BackOffice.UserProxy.BaseEntityOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isEnableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isEnable {
            get {
                return this.isEnableField;
            }
            set {
                if ((this.isEnableField.Equals(value) != true)) {
                    this.isEnableField = value;
                    this.RaisePropertyChanged("isEnable");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserProxy.UserContract")]
    public interface UserContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/GetByIdResponse")]
        BackOffice.UserProxy.User GetById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/GetById", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/GetByIdResponse")]
        System.Threading.Tasks.Task<BackOffice.UserProxy.User> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/InsertResponse")]
        BackOffice.UserProxy.User Insert(BackOffice.UserProxy.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/Insert", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/InsertResponse")]
        System.Threading.Tasks.Task<BackOffice.UserProxy.User> InsertAsync(BackOffice.UserProxy.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/UpdateResponse")]
        BackOffice.UserProxy.User Update(BackOffice.UserProxy.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/UpdateResponse")]
        System.Threading.Tasks.Task<BackOffice.UserProxy.User> UpdateAsync(BackOffice.UserProxy.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/SearchForResponse")]
        BackOffice.UserProxy.User[] SearchFor(System.Func<BackOffice.UserProxy.User, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/SearchFor", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/SearchForResponse")]
        System.Threading.Tasks.Task<BackOffice.UserProxy.User[]> SearchForAsync(System.Func<BackOffice.UserProxy.User, bool> predicate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/GetAllResponse")]
        BackOffice.UserProxy.User[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Int32_User/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Int32_User/GetAllResponse")]
        System.Threading.Tasks.Task<BackOffice.UserProxy.User[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserContract/Login", ReplyAction="http://tempuri.org/UserContract/LoginResponse")]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserContract/Login", ReplyAction="http://tempuri.org/UserContract/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserContractChannel : BackOffice.UserProxy.UserContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserContractClient : System.ServiceModel.ClientBase<BackOffice.UserProxy.UserContract>, BackOffice.UserProxy.UserContract {
        
        public UserContractClient() {
        }
        
        public UserContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BackOffice.UserProxy.User GetById(int id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<BackOffice.UserProxy.User> GetByIdAsync(int id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public BackOffice.UserProxy.User Insert(BackOffice.UserProxy.User entity) {
            return base.Channel.Insert(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.UserProxy.User> InsertAsync(BackOffice.UserProxy.User entity) {
            return base.Channel.InsertAsync(entity);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public BackOffice.UserProxy.User Update(BackOffice.UserProxy.User entity) {
            return base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task<BackOffice.UserProxy.User> UpdateAsync(BackOffice.UserProxy.User entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public BackOffice.UserProxy.User[] SearchFor(System.Func<BackOffice.UserProxy.User, bool> predicate) {
            return base.Channel.SearchFor(predicate);
        }
        
        public System.Threading.Tasks.Task<BackOffice.UserProxy.User[]> SearchForAsync(System.Func<BackOffice.UserProxy.User, bool> predicate) {
            return base.Channel.SearchForAsync(predicate);
        }
        
        public BackOffice.UserProxy.User[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BackOffice.UserProxy.User[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
    }
}
