// <auto-generated />
namespace BackOffice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class base64image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(base64image));
        
        string IMigrationMetadata.Id
        {
            get { return "201406271513313_base64image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
